# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20160405_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
