# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20160405_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='retweet_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
