# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_album_retweet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
    ]
